export const TOUR_DATES = [
  { Date: "08/05", city: "West Palm Beach", state: "FL" },
  { Date: "08/06", city: "Tampa", state: "FL" },
  { Date: "08/08", city: "Atlanta", state: "GA" },
  { Date: "08/09", city: "Nashville", state: "TN" },
  { Date: "08/12", city: "Maryland Heights", state: "MO" },
  { Date: "08/13", city: "Noblesville", state: "IN" },
  { Date: "08/15", city: "Somerset", state: "WI" },
  { Date: "08/16", city: "Milwaukee", state: "WI" },
  { Date: "08/17", city: "Tinley Park", state: "IL" },
  { Date: "08/19", city: "Denver", state: "CO" },
  { Date: "08/22", city: "Las Vegas", state: "NV" },
  { Date: "08/23", city: "Salt Lake City", state: "UT" },
  { Date: "08/24", city: "Nampa", state: "ID" },
  { Date: "08/26", city: "Ridgefield", state: "WA" },
  { Date: "08/27", city: "Auburn", state: "WA" },
  { Date: "08/29", city: "Vancouver", state: "BC" },
  { Date: "09/02", city: "Wheatland", state: "CA" },
  { Date: "09/03", city: "Mountain View", state: "CA" },
  { Date: "09/05", city: "Los Angeles", state: "CA" },
  { Date: "09/06", city: "Chula Vista", state: "CA" },
  { Date: "09/08", city: "Phoenix", state: "AZ" },
  { Date: "09/10", city: "Albuquerque", state: "NM" },
  { Date: "09/12", city: "Austin", state: "TX" },
  { Date: "09/13", city: "Dallas", state: "TX" },
  { Date: "09/14", city: "Tulsa", state: "OK" },
  { Date: "09/16", city: "Clarkston", state: "MI" },
  { Date: "09/17", city: "Cincinnati", state: "OH" },
  { Date: "09/19", city: "Bristow", state: "VA" },
  { Date: "09/20", city: "Burgettstown", state: "PA" },
  { Date: "09/21", city: "Louisville", state: "KY" },
  { Date: "09/23", city: "Hartford", state: "CT" },
  { Date: "09/24", city: "Mansfield", state: "MA" },
  { Date: "09/26", city: "Montreal", state: "QC" },
  { Date: "09/27", city: "Toronto", state: "ON" },
  { Date: "09/28", city: "Darien Center", state: "NY" },
  { Date: "09/30", city: "Holmdel", state: "NJ" },
  { Date: "10/01", city: "Camden", state: "NJ" },
  { Date: "10/03", city: "Wantagh", state: "NY" },
  { Date: "10/04", city: "Virginia Beach", state: "VA" },
  { Date: "10/05", city: "Raleigh", state: "NC" },
  { Date: "10/07", city: "Charlotte", state: "NC" },
  { Date: "10/08", city: "Simpsonville", state: "SC" },
  { Date: "10/10", city: "Houston", state: "TX" },
  { Date: "10/11", city: "New Orleans", state: "LA" },
];
