import { CDN_URL } from "@/utils";

export const SLIDES = [
  {
    name: "$uicideboy$",
    icon: `${CDN_URL}/images/artists/sb-icon.png`,
    bg: `${CDN_URL}/images/backgrounds/grunge-0.png`,
    bio: `Ruby Da Cherry & $crim, founders of the grey.`,
    youtube: "https://www.youtube.com/@suicideboys-G59",
    ig: "https://www.instagram.com/suicideboys",
    x: "https://x.com/SUICIDEBOYS",
    spotify: "https://open.spotify.com/artist/1VPmR4DJC1PlOtd0IADAO0",
    apple: "https://music.apple.com/ca/artist/%24uicideboy%24/1081606072",
    soundcloud: "https://soundcloud.com/g59",
    tiktok: "https://www.tiktok.com/@suicideboys",
  },
  {
    name: "night lovell",
    icon: `${CDN_URL}/images/artists/nightlovell-icon.png`,
    bg: `${CDN_URL}/images/backgrounds/grunge-0.png`,
    bio: `dark night rises.`,
    youtube: "https://www.youtube.com/channel/UCjwf9oA4C9Yzxcg4vjI5GDg",
    ig: "https://www.instagram.com/nightlovell",
    x: "https://x.com/nightlovell",
    spotify: "https://open.spotify.com/artist/2y246nnP9pQT0E6v3ZMMOO",
    soundcloud: "https://soundcloud.com/night_lovell",
    tiktok: "https://www.tiktok.com/@nightlovell",
  },
  {
    name: "shakewell",
    icon: `${CDN_URL}/images/artists/sw4-icon.png`,
    bg: `${CDN_URL}/images/backgrounds/grunge-2.png`,
    bio: `shameless, smg warrior.`,
    youtube: "https://www.youtube.com/@shakewellmusic3699",
    ig: "https://www.instagram.com/shakewell",
    x: "https://x.com/ShakeWell818",
    spotify: "https://open.spotify.com/artist/1w7GLktHE8w0aEhhaZ0QKB",
    soundcloud: "https://soundcloud.com/shakewell818",
  },
  {
    name: "germ",
    icon: `${CDN_URL}/images/artists/germ-icon.png`,
    bg: `${CDN_URL}/images/backgrounds/grunge-2.png`,
    bio: `fire spitta, wood grain whipper.`,
    youtube: "https://www.youtube.com/channel/UC-_UDTQXbfW30ljoYmvCIAQ",
    ig: "https://www.instagram.com/germ",
    x: "https://x.com/germjeezus",
    spotify: "https://open.spotify.com/artist/4OYIkXBBN6ET96coWyWAXh",
    soundcloud: "https://soundcloud.com/germone",
  },
  {
    name: "chetta",
    icon: `${CDN_URL}/images/artists/chetta-icon.png`,
    bg: `${CDN_URL}/images/backgrounds/grunge-1.png`,
    bio: `guess who, bitch.`,
    youtube: "https://www.youtube.com/@CHETTA",
    ig: "https://www.instagram.com/j_chetta",
    x: "https://x.com/j_chetta",
    spotify: "https://open.spotify.com/artist/7ipVTAf9PqCSddkeYtKw9h",
    soundcloud: "https://soundcloud.com/j-chetta",
    tiktok: "https://www.tiktok.com/@j_chetta",
  },

  {
    name: "duckboy",
    icon: `${CDN_URL}/images/artists/db2-icon.png`,
    bg: `${CDN_URL}/images/backgrounds/grunge-4.png`,
    bio: `where y'at duckboy?`,
    youtube: "https://www.youtube.com/@whereyatduckboy",
    ig: "https://www.instagram.com/whereyatduckboy",
    x: "https://x.com/whereyatduckboy",
    spotify: "https://open.spotify.com/artist/7LcRxOTDhbQ19ulgIVOWpu",
    soundcloud: "https://soundcloud.com/whereyatduckboy",
    tiktok: "https://www.tiktok.com/@whereyatduckboy1",
    web: "https://www.duckboy.net",
  },
  {
    name: "lonely boy",
    icon: `${CDN_URL}/images/artists/lonelyboy-icon.png`,
    bg: `${CDN_URL}/images/backgrounds/grunge-3.png`,
    bio: `such a lonely boy.`,
    youtube: "https://www.youtube.com/channel/UCdtCvK-ERe6HD-yS_F9--Ig",
    ig: "https://www.instagram.com/lonelyboy",
    x: "https://x.com/SuicideChrist",
    spotify: "https://open.spotify.com/artist/5VKvqCyBxqbaXUp8eK0aUy",
    soundcloud: "https://soundcloud.com/scrim",
    tiktok: "https://www.tiktok.com/@lonelyyboyy.1",
  },
];

export const TOUR_DATES = [
  { date: "08/05", city: "West Palm Beach", state: "FL", left: 82, top: 85 },
  { date: "08/06", city: "Tampa", state: "FL", left: 78, top: 83 },
  { date: "08/08", city: "Atlanta", state: "GA", left: 74, top: 65 },
  { date: "08/09", city: "Nashville", state: "TN", left: 68, top: 55 },
  { date: "08/12", city: "Maryland Heights", state: "MO", left: 60, top: 48 },
  { date: "08/13", city: "Noblesville", state: "IN", left: 68, top: 40 },
  { date: "08/15", city: "Somerset", state: "WI", left: 56, top: 20 },
  { date: "08/16", city: "Milwaukee", state: "WI", left: 63, top: 25 },
  { date: "08/17", city: "Tinley Park", state: "IL", left: 64, top: 33 },
  { date: "08/19", city: "Denver", state: "CO", left: 32, top: 40 },
  { date: "08/22", city: "Las Vegas", state: "NV", left: 12, top: 48 },
  { date: "08/23", city: "Salt Lake City", state: "UT", left: 25, top: 45 },
  { date: "08/24", city: "Nampa", state: "ID", left: 22, top: 35 },
  { date: "08/26", city: "Ridgefield", state: "WA", left: 5, top: 18 },
  { date: "08/27", city: "Auburn", state: "WA", left: 7, top: 8 },
  { date: "09/02", city: "Wheatland", state: "CA", left: 8, top: 48 },
  { date: "09/03", city: "Mountain View", state: "CA", left: 6, top: 50 },
  { date: "09/05", city: "Los Angeles", state: "CA", left: 4, top: 53 },
  { date: "09/06", city: "Chula Vista", state: "CA", left: 6, top: 58 },
  { date: "09/08", city: "Phoenix", state: "AZ", left: 18, top: 61 },
  { date: "09/10", city: "Albuquerque", state: "NM", left: 30, top: 58 },
  { date: "09/12", city: "Austin", state: "TX", left: 49, top: 77 },
  { date: "09/13", city: "Dallas", state: "TX", left: 50, top: 70 },
  { date: "09/14", city: "Tulsa", state: "OK", left: 48, top: 53 },
  { date: "09/16", city: "Clarkston", state: "MI", left: 71, top: 26 },
  { date: "09/17", city: "Cincinnati", state: "OH", left: 72, top: 40 },
  { date: "09/19", city: "Bristow", state: "VA", left: 82, top: 40 },
  { date: "09/20", city: "Burgettstown", state: "PA", left: 78, top: 35 },
  { date: "09/21", city: "Louisville", state: "KY", left: 70, top: 48 },
  { date: "09/23", city: "Hartford", state: "CT", left: 90, top: 25 },
  { date: "09/24", city: "Mansfield", state: "MA", left: 93, top: 23 },
  { date: "09/28", city: "Darien Center", state: "NY", left: 82, top: 22 },
  { date: "09/30", city: "Holmdel", state: "NJ", left: 86, top: 33 },
  { date: "10/01", city: "Camden", state: "NJ", left: 84, top: 34 },
  { date: "10/03", city: "Wantagh", state: "NY", left: 88, top: 30 },
  { date: "10/04", city: "Virginia Beach", state: "VA", left: 88, top: 48 },
  { date: "10/05", city: "Raleigh", state: "NC", left: 84, top: 52 },
  { date: "10/07", city: "Charlotte", state: "NC", left: 80, top: 56 },
  { date: "10/08", city: "Simpsonville", state: "SC", left: 78, top: 60 },
  { date: "10/10", city: "Houston", state: "TX", left: 52, top: 78 },
  { date: "10/11", city: "New Orleans", state: "LA", left: 62, top: 82 },
  { date: "08/29", city: "Vancouver", state: "BC", left: 5, top: 0 },
  { date: "09/26", city: "Montreal", state: "QC", left: 80, top: 15 },
  { date: "09/27", city: "Toronto", state: "ON", left: 77, top: 23 },
];

export const TOURS = TOUR_DATES.map((tour) => ({
  ...tour,
  date: new Date(`2025-${tour.date.replace("/", "-")}`),
}));
