export const SLIDES = [
  {
    name: "$uicideboy$",
    icon: "/images/artists/sb-icon.png",
    bg: "/images/backgrounds/grunge-0.png",
    bio: `Ruby Da Cherry & $crim, founders of the grey.`,
    youtube: "https://www.youtube.com/@suicideboys-G59",
    ig: "https://www.instagram.com/suicideboys",
    x: "https://x.com/SUICIDEBOYS",
    spotify: "https://open.spotify.com/artist/1VPmR4DJC1PlOtd0IADAO0",
    apple: "https://music.apple.com/ca/artist/%24uicideboy%24/1081606072",
    soundcloud: "https://soundcloud.com/g59",
    tiktok: "https://www.tiktok.com/@suicideboys",
  },
  {
    name: "night lovell",
    icon: "/images/artists/nightlovell-icon.png",
    bg: "/images/backgrounds/grunge-0.png",
    bio: `dark night rises.`,
    youtube: "https://www.youtube.com/channel/UCjwf9oA4C9Yzxcg4vjI5GDg",
    ig: "https://www.instagram.com/nightlovell",
    x: "https://x.com/nightlovell",
    spotify: "https://open.spotify.com/artist/2y246nnP9pQT0E6v3ZMMOO",
    soundcloud: "https://soundcloud.com/night_lovell",
    tiktok: "https://www.tiktok.com/@nightlovell",
  },
  {
    name: "shakewell",
    icon: "/images/artists/sw4-icon.png",
    bg: "/images/backgrounds/grunge-2.png",
    bio: `shameless, smg warrior.`,
    youtube: "https://www.youtube.com/@shakewellmusic3699",
    ig: "https://www.instagram.com/shakewell",
    x: "https://x.com/ShakeWell818",
    spotify: "https://open.spotify.com/artist/1w7GLktHE8w0aEhhaZ0QKB",
    soundcloud: "https://soundcloud.com/shakewell818",
  },
  {
    name: "germ",
    icon: "/images/artists/germ-icon.png",
    bg: "/images/backgrounds/grunge-2.png",
    bio: `fire spitta, wood grain whipper.`,
    youtube: "https://www.youtube.com/channel/UC-_UDTQXbfW30ljoYmvCIAQ",
    ig: "https://www.instagram.com/germ",
    x: "https://x.com/germjeezus",
    spotify: "https://open.spotify.com/artist/4OYIkXBBN6ET96coWyWAXh",
    soundcloud: "https://soundcloud.com/germone",
  },
  {
    name: "chetta",
    icon: "/images/artists/chetta-icon.png",
    bg: "/images/backgrounds/grunge-1.png",
    bio: `guess who, bitch.`,
    youtube: "https://www.youtube.com/@CHETTA",
    ig: "https://www.instagram.com/j_chetta",
    x: "https://x.com/j_chetta",
    spotify: "https://open.spotify.com/artist/7ipVTAf9PqCSddkeYtKw9h",
    soundcloud: "https://soundcloud.com/j-chetta",
    tiktok: "https://www.tiktok.com/@j_chetta",
  },

  {
    name: "duckboy",
    icon: "/images/artists/db2-icon.png",
    bg: "/images/backgrounds/grunge-4.png",
    bio: `where y'at duckboy?`,
    youtube: "https://www.youtube.com/@whereyatduckboy",
    ig: "https://www.instagram.com/whereyatduckboy",
    x: "https://x.com/whereyatduckboy",
    spotify: "https://open.spotify.com/artist/7LcRxOTDhbQ19ulgIVOWpu",
    soundcloud: "https://soundcloud.com/whereyatduckboy",
    tiktok: "https://www.tiktok.com/@whereyatduckboy1",
    web: "https://www.duckboy.net",
  },
  {
    name: "lonely boy",
    icon: "/images/artists/lonelyboy-icon.png",
    bg: "/images/backgrounds/grunge-3.png",
    bio: `such a lonely boy.`,
    youtube: "https://www.youtube.com/channel/UCdtCvK-ERe6HD-yS_F9--Ig",
    ig: "https://www.instagram.com/lonelyboy",
    x: "https://x.com/SuicideChrist",
    spotify: "https://open.spotify.com/artist/5VKvqCyBxqbaXUp8eK0aUy",
    soundcloud: "https://soundcloud.com/scrim",
    tiktok: "https://www.tiktok.com/@lonelyyboyy.1",
  },
];
